services:
  accounts:
    image: "guneetbh/accounts:v1"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - micro
  cards:
    image: "guneetbh/cards:v1"
    container_name: cards-ms
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - micro
  loans:
    image: "guneetbh/loans:v1"
    container_name: loads-ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - micro
networks:
  micro:
    driver: "bridge"