spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "2.0"

accounts:
  message: "Welcome to TBank accounts related local APIs"
  contactDetails:
    name: "Smith Ryan - QA-Lead"
    email: "smith@tbank.com"
  onCallSupport:
    - (666) 265-3765
    - (666) 734-8371
